baseURL = "/"
languageCode = "en-us"
title = "Tech Notes"
theme = "anubis"
paginate = 10
disqusShortname = "technotes-3"
googleAnalytics = "UA-162169622-1"

[author]
  name = "Atul Pandey"

[params]
author = "Atul Pandey"
description = ""
env = "production"

[menu]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 2

[[menu.main]]
identifier = "archive"
name = "Archive"
title = "Archive"
url =  "/posts/"
weight = "3"